//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: worldData.proto
namespace worldProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldMessage")]
  public partial class WorldMessage : global::ProtoBuf.IExtensible
  {
    public WorldMessage() {}
    
    private readonly global::System.Collections.Generic.List<worldProto.RowMessage> _tileArray = new global::System.Collections.Generic.List<worldProto.RowMessage>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tileArray", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<worldProto.RowMessage> tileArray
    {
      get { return _tileArray; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RowMessage")]
  public partial class RowMessage : global::ProtoBuf.IExtensible
  {
    public RowMessage() {}
    
    private readonly global::System.Collections.Generic.List<worldProto.TileDataMessage> _row = new global::System.Collections.Generic.List<worldProto.TileDataMessage>();
    [global::ProtoBuf.ProtoMember(1, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<worldProto.TileDataMessage> row
    {
      get { return _row; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileDataMessage")]
  public partial class TileDataMessage : global::ProtoBuf.IExtensible
  {
    public TileDataMessage() {}
    
    private int _tileType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tileType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileType
    {
      get { return _tileType; }
      set { _tileType = value; }
    }
    private int _enemyCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"enemyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enemyCount
    {
      get { return _enemyCount; }
      set { _enemyCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}