# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worldData.proto',
  package='worldProto',
  serialized_pb=_b('\n\x0fworldData.proto\x12\nworldProto\"9\n\x0cWorldMessage\x12)\n\ttileArray\x18\x01 \x03(\x0b\x32\x16.worldProto.RowMessage\"6\n\nRowMessage\x12(\n\x03row\x18\x01 \x03(\x0b\x32\x1b.worldProto.TileDataMessage\"7\n\x0fTileDataMessage\x12\x10\n\x08tileType\x18\x01 \x02(\x05\x12\x12\n\nenemyCount\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WORLDMESSAGE = _descriptor.Descriptor(
  name='WorldMessage',
  full_name='worldProto.WorldMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tileArray', full_name='worldProto.WorldMessage.tileArray', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=88,
)


_ROWMESSAGE = _descriptor.Descriptor(
  name='RowMessage',
  full_name='worldProto.RowMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='worldProto.RowMessage.row', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=144,
)


_TILEDATAMESSAGE = _descriptor.Descriptor(
  name='TileDataMessage',
  full_name='worldProto.TileDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tileType', full_name='worldProto.TileDataMessage.tileType', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enemyCount', full_name='worldProto.TileDataMessage.enemyCount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=201,
)

_WORLDMESSAGE.fields_by_name['tileArray'].message_type = _ROWMESSAGE
_ROWMESSAGE.fields_by_name['row'].message_type = _TILEDATAMESSAGE
DESCRIPTOR.message_types_by_name['WorldMessage'] = _WORLDMESSAGE
DESCRIPTOR.message_types_by_name['RowMessage'] = _ROWMESSAGE
DESCRIPTOR.message_types_by_name['TileDataMessage'] = _TILEDATAMESSAGE

WorldMessage = _reflection.GeneratedProtocolMessageType('WorldMessage', (_message.Message,), dict(
  DESCRIPTOR = _WORLDMESSAGE,
  __module__ = 'worldData_pb2'
  # @@protoc_insertion_point(class_scope:worldProto.WorldMessage)
  ))
_sym_db.RegisterMessage(WorldMessage)

RowMessage = _reflection.GeneratedProtocolMessageType('RowMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROWMESSAGE,
  __module__ = 'worldData_pb2'
  # @@protoc_insertion_point(class_scope:worldProto.RowMessage)
  ))
_sym_db.RegisterMessage(RowMessage)

TileDataMessage = _reflection.GeneratedProtocolMessageType('TileDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _TILEDATAMESSAGE,
  __module__ = 'worldData_pb2'
  # @@protoc_insertion_point(class_scope:worldProto.TileDataMessage)
  ))
_sym_db.RegisterMessage(TileDataMessage)


# @@protoc_insertion_point(module_scope)
